// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjS1YTMSXbaaXrUgfuDgyXqT2O95cKU8s',
    appId: '1:395881301876:android:b683a8cfd1fd0439c68e21',
    messagingSenderId: '395881301876',
    projectId: 'chat-app-e9f41',
    storageBucket: 'chat-app-e9f41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBozpXU1sblEdogdYQGYi4bPDSpRNwo16I',
    appId: '1:395881301876:ios:4b5484a50548ab34c68e21',
    messagingSenderId: '395881301876',
    projectId: 'chat-app-e9f41',
    storageBucket: 'chat-app-e9f41.appspot.com',
    androidClientId: '395881301876-jobgc5n36dssvt6gvc9hrg1ln4qmmgrt.apps.googleusercontent.com',
    iosClientId: '395881301876-hkq8nmrv0qg99b4cjrgie8lrepfaup0r.apps.googleusercontent.com',
    iosBundleId: 'com.gunjon.chatapp',
  );
}
